export let jobOffersData = [
    {   
        id: 1,
        name: "Customer Service Specialist with English",
        location: "Kraków",
        date: "12-12-2020",
        department: "Supply Chain / Planning / Customer Service",
        'employment type': "Full-Time",
        'position description': 'Process incoming orders in SAP software, Review customers’ orders to ensure completeness and correctness of delivery instructions, Cooperate with customers, sales, operations and finance, Invoice customers in accordance with relevant documentation, Provide phone and email support to both customers and sales team, Log all order and logistics complaints from customers, Process correction of invoices according to information provided by customers',
        'position requirements': 'English language skills proficiency, both oral and written, First experience in order management or customer care area would be beneficial, MS-Office knowledge, Knowledge of SAP would be an advantage, Knowledge of SFDC CRM would be an advantage',
        'personal requirements': 'Excellent interpersonal and communication abilities, Ability to work in a team environment, Ability to multi-task and work in a fast paced environment, Ability to learn quickly and resolve customer inquiries',
        'what we offer': 'Possibility to develop in an international company, Training and development programs, Private medical care, Group Life Insurance, Multisport card, Flexible benefits platform, Language classes, Pension Scheme (PPE) after 12 months, Childcare subsidy, Happy Mondays :), Friendly atmosphere, Casual dress code, Attractive location in city center',
    },
    {   
        id: 2,
        name: "Customer Service Specialist with German",
        location: "Kraków",
        date: "18-12-2020",
        department: "Supply Chain / Planning / Customer Service",
        'employment type': "Full-Time",
        'position description': 'Process incoming orders in SAP software, Review customers’ orders to ensure completeness and correctness of delivery instructions, Cooperate with customers, sales, operations and finance, Invoice customers in accordance with relevant documentation, Provide phone and email support to both customers and sales team, Log all order and logistics complaints from customers, Process correction of invoices according to information provided by customers',
        'position requirements': 'German language skills proficiency, both oral and written, First experience in order management or customer care area would be beneficial, MS-Office knowledge, Knowledge of SAP would be an advantage, Knowledge of SFDC CRM would be an advantage',
        'personal requirements': 'Excellent interpersonal and communication abilities, Ability to work in a team environment, Ability to multi-task and work in a fast paced environment, Ability to learn quickly and resolve customer inquiries',
        'what we offer': 'Possibility to develop in an international company, Training and development programs, Private medical care, Group Life Insurance, Multisport card, Flexible benefits platform, Language classes, Pension Scheme (PPE) after 12 months, Childcare subsidy, Happy Mondays :), Friendly atmosphere, Casual dress code, Attractive location in city center',
    },
    {   
        id: 3,
        name: "Front-end Developer",
        location: "remote",
        date: "12-12-2020",
        department: "IT",
        'employment type': "Full-Time",
        'position description': 'Taking a business problem and come up with the technical strategy (push vs pull etc, real time vs batches, sync vs async) within the team, high level design and lead the implementation, Collaborating with SDEs across teams working on the same or similar business problem, Influencing team’s technical and business strategy by suggesting novel approaches, Being able to communicate ideas and get feedback from different stakeholders and drive convergence to achieve the right outcomes, Ensuring design or architectural deficiencies are addressed, Consistently leading delivery of valuable features, Proposing and driving process improvements, Helping elaborate requirements where necessary',
        'position requirements': 'In-depth knowledge of user interface models, application design, and website functionality, Proficient knowledge of SPA frameworks (React, Angular), Proficient knowledge of CSS3, HTML5, jQuery and Ajax, Experience using GIT, Good communication skills in English language (reading, writing, speaking)',
        'personal requirements': 'Excellent interpersonal and communication abilities, Ability to work in a team environment, Ability to multi-task and work in a fast paced environment, Ability to learn quickly and resolve customer inquiries',
        'what we offer': 'Possibility to develop in an international company, Training and development programs, Private medical care, Group Life Insurance, Multisport card, Flexible benefits platform, Language classes, Pension Scheme (PPE) after 12 months, Childcare subsidy, Happy Mondays :), Friendly atmosphere, Casual dress code, Attractive location in city center',
    },
    {   
        id: 4,
        name: "Office Administrator",
        location: "Radom",
        date: "05-01-2021",
        department: "Administration",
        'employment type': "Full-Time",
        'position description': 'Handling of Customer Service tasks according to company standards (e.g. processing orders and enquiries, providing information on products, prices, analysing demand forecasts, etc.), Developing strong customer relations and implementing customer service policies and procedures, Cooperating with other departments of the company in order to provide the highest level of customer service experience, Interacting with customers via email and phone, Handling of customer issues (receiving and managing customer complaints, resolving product returns, reporting), Managing production contracts realisation (entering customer orders into the database system, supporting production planning and prioritisation, monitoring the execution of orders), Administrative support to the management of the company and other team members, Conducting various office/ admin tasks (e.g. verification and filing of invoices, ordering office supplies, etc.), Ensuring proper circulation of documents',
        'position requirements': 'Previous work experience in a similar role (preferably in a print/production industry), Customer oriented attitude and focus on providing the best customer service experience, Very good communication, organisational, planning and prioritisation skills, A confident and professional telephone manner, High level of accuracy and attention to details, Proficiency in MS Office applications, Fluent written and spoken English is a must, Min. secondary education, Resilience to stress and ability to multi-task under pressure',
        'personal requirements': 'Excellent interpersonal and communication abilities, Ability to work in a team environment, Ability to multi-task and work in a fast paced environment, Ability to learn quickly and resolve customer inquiries',
        'what we offer': 'Possibility to develop in an international company, Training and development programs, Private medical care, Group Life Insurance, Multisport card, Flexible benefits platform, Language classes, Pension Scheme (PPE) after 12 months, Childcare subsidy, Happy Mondays :), Friendly atmosphere, Casual dress code, Attractive location in city center',
    },
];